import type { HeroCounterpick, HeroId } from "./types";

/**
 * Initial counterpick reference. Each entry belongs to the target hero and lists
 * heroes that can answer it. Scores deliberately start at 1 until they are
 * backed by a more detailed matchup guide.
 */
export const counterpicksByTargetId: Record<HeroId, HeroCounterpick[]> = {
  abala: [],
  adora: [],
  akmon: [],
  amanda: [],
  aolmond: [],
  aruru: [],
  ash: [],
  babu: [],
  bahzam: [],
  bella: [],
  benzel: [{ heroId: "adora", rating: 1 }],
  calix: [],
  carmen: [{ heroId: "adora", rating: 1 }],
  chiron: [],
  coco: [],
  dextor: [],
  dmitri: [],
  dolucos: [],
  elara: [],
  feruki: [],
  fiona: [],
  fleta: [],
  galan: [],
  harfa: [],
  idina: [],
  jack: [],
  kaion: [],
  karim: [],
  ken: [],
  kyle: [],
  lagou: [],
  lena: [],
  leovalt: [{ heroId: "zeke", rating: 1 }],
  liandra: [],
  lilith: [],
  louveti: [],
  lulu: [],
  lumen: [],
  lupico: [],
  melantha: [],
  milia: [],
  morra: [],
  muerte: [],
  naru: [],
  nebula: [],
  nevir: [{ heroId: "zeke", rating: 1 }],
  nox: [],
  nuel: [],
  odelia: [],
  olga: [],
  oneiric: [],
  paopao: [],
  paru: [],
  rael: [],
  rakan: [],
  richelle: [{ heroId: "benzel", rating: 1 }],
  ripper: [],
  roze: [],
  sander: [],
  scarlet: [],
  sekhrus: [],
  serena: [],
  shabeck: [],
  sol: [],
  solina: [],
  tania: [],
  taros: [],
  telfer: [],
  ulion: [],
  vescura: [],
  void: [],
  zagrako: [],
  zeke: [],
  zenon: [],
};
