/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SoulStoneCalculatorRouteImport } from './routes/soul-stone-calculator'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SoulStoneCalculatorRoute = SoulStoneCalculatorRouteImport.update({
  id: '/soul-stone-calculator',
  path: '/soul-stone-calculator',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/soul-stone-calculator': typeof SoulStoneCalculatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/soul-stone-calculator': typeof SoulStoneCalculatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/soul-stone-calculator': typeof SoulStoneCalculatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/soul-stone-calculator'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/soul-stone-calculator'
  id: '__root__' | '/' | '/soul-stone-calculator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SoulStoneCalculatorRoute: typeof SoulStoneCalculatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soul-stone-calculator': {
      id: '/soul-stone-calculator'
      path: '/soul-stone-calculator'
      fullPath: '/soul-stone-calculator'
      preLoaderRoute: typeof SoulStoneCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SoulStoneCalculatorRoute: SoulStoneCalculatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
