/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as TeamBuilderRouteImport } from "./routes/team-builder";
import { Route as SupportRouteImport } from "./routes/support";
import { Route as SoulStoneCalculatorRouteImport } from "./routes/soul-stone-calculator";
import { Route as HeroesRouteImport } from "./routes/heroes";
import { Route as CounterpickRouteImport } from "./routes/counterpick";
import { Route as AdminRouteImport } from "./routes/admin";
import { Route as IndexRouteImport } from "./routes/index";

const TeamBuilderRoute = TeamBuilderRouteImport.update({
  id: "/team-builder",
  path: "/team-builder",
  getParentRoute: () => rootRouteImport,
} as any);
const SupportRoute = SupportRouteImport.update({
  id: "/support",
  path: "/support",
  getParentRoute: () => rootRouteImport,
} as any);
const SoulStoneCalculatorRoute = SoulStoneCalculatorRouteImport.update({
  id: "/soul-stone-calculator",
  path: "/soul-stone-calculator",
  getParentRoute: () => rootRouteImport,
} as any);
const HeroesRoute = HeroesRouteImport.update({
  id: "/heroes",
  path: "/heroes",
  getParentRoute: () => rootRouteImport,
} as any);
const CounterpickRoute = CounterpickRouteImport.update({
  id: "/counterpick",
  path: "/counterpick",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminRoute = AdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/admin": typeof AdminRoute;
  "/counterpick": typeof CounterpickRoute;
  "/heroes": typeof HeroesRoute;
  "/soul-stone-calculator": typeof SoulStoneCalculatorRoute;
  "/support": typeof SupportRoute;
  "/team-builder": typeof TeamBuilderRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/admin": typeof AdminRoute;
  "/counterpick": typeof CounterpickRoute;
  "/heroes": typeof HeroesRoute;
  "/soul-stone-calculator": typeof SoulStoneCalculatorRoute;
  "/support": typeof SupportRoute;
  "/team-builder": typeof TeamBuilderRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/admin": typeof AdminRoute;
  "/counterpick": typeof CounterpickRoute;
  "/heroes": typeof HeroesRoute;
  "/soul-stone-calculator": typeof SoulStoneCalculatorRoute;
  "/support": typeof SupportRoute;
  "/team-builder": typeof TeamBuilderRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/admin"
    | "/counterpick"
    | "/heroes"
    | "/soul-stone-calculator"
    | "/support"
    | "/team-builder";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/admin"
    | "/counterpick"
    | "/heroes"
    | "/soul-stone-calculator"
    | "/support"
    | "/team-builder";
  id:
    | "__root__"
    | "/"
    | "/admin"
    | "/counterpick"
    | "/heroes"
    | "/soul-stone-calculator"
    | "/support"
    | "/team-builder";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AdminRoute: typeof AdminRoute;
  CounterpickRoute: typeof CounterpickRoute;
  HeroesRoute: typeof HeroesRoute;
  SoulStoneCalculatorRoute: typeof SoulStoneCalculatorRoute;
  SupportRoute: typeof SupportRoute;
  TeamBuilderRoute: typeof TeamBuilderRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/team-builder": {
      id: "/team-builder";
      path: "/team-builder";
      fullPath: "/team-builder";
      preLoaderRoute: typeof TeamBuilderRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/support": {
      id: "/support";
      path: "/support";
      fullPath: "/support";
      preLoaderRoute: typeof SupportRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/soul-stone-calculator": {
      id: "/soul-stone-calculator";
      path: "/soul-stone-calculator";
      fullPath: "/soul-stone-calculator";
      preLoaderRoute: typeof SoulStoneCalculatorRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/heroes": {
      id: "/heroes";
      path: "/heroes";
      fullPath: "/heroes";
      preLoaderRoute: typeof HeroesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/counterpick": {
      id: "/counterpick";
      path: "/counterpick";
      fullPath: "/counterpick";
      preLoaderRoute: typeof CounterpickRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin": {
      id: "/admin";
      path: "/admin";
      fullPath: "/admin";
      preLoaderRoute: typeof AdminRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CounterpickRoute: CounterpickRoute,
  HeroesRoute: HeroesRoute,
  SoulStoneCalculatorRoute: SoulStoneCalculatorRoute,
  SupportRoute: SupportRoute,
  TeamBuilderRoute: TeamBuilderRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
